package Formularios;

import Datos.ArchivoAutor;
import Datos.Autor;
import Datos.ConexionOracol;
import Logico.GestionAutor;
import Logico.GestionLibro;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FAutor extends javax.swing.JDialog {

    /**
     * Creates new form FAutor
     */
    public FAutor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tablaAutor.setModel(GestionAutor.getModeloAutor());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAutor = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        jLabel1.setText("Pais de origen");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 100, 80, 27);
        jPanel2.add(txtPais);
        txtPais.setBounds(110, 100, 80, 27);

        jLabel2.setText("Identificacion");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 10, 80, 27);

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel2.add(txtid);
        txtid.setBounds(110, 10, 80, 27);

        jLabel3.setText("Apellido");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 70, 80, 27);
        jPanel2.add(txtApellido);
        txtApellido.setBounds(110, 70, 80, 27);

        jLabel4.setText("Nombre");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 40, 80, 27);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre);
        txtNombre.setBounds(110, 40, 80, 27);

        tablaAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAutorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAutor);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(250, 20, 390, 230);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconfinder-trash-4341321_120557.png"))); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(20, 170, 109, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1486485588-add-create-new-math-sign-cross-plus_81186.png"))); // NOI18N
        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(20, 140, 109, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/emblemunreadable_93487.png"))); // NOI18N
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(473, 260, 110, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 650, 300);

        setSize(new java.awt.Dimension(668, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            agregar();
        } catch (SQLException ex) {
            Logger.getLogger(FAutor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        eliminar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAutorMouseClicked
        pintar(tablaAutor.rowAtPoint(evt.getPoint()));
    }//GEN-LAST:event_tablaAutorMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void pintar(int numero){
       
        txtid.setText(String.valueOf(tablaAutor.getValueAt(numero, 0)));
        txtNombre.setText(String.valueOf(tablaAutor.getValueAt(numero, 1)));
        txtApellido.setText(String.valueOf(tablaAutor.getValueAt(numero, 2)));
        txtPais.setText(String.valueOf(tablaAutor.getValueAt(numero, 3)));
    }
    
    private void eliminar(){
        String respuesta = GestionAutor.eliminarAutor(txtid.getText().trim());
        JOptionPane.showMessageDialog(this, respuesta);
         tablaAutor.setModel(GestionAutor.getModeloAutor());
         limpiar();
        
    }
    
    
    
    
    private void agregar() throws SQLException {
        String respuesta = GestionAutor.registrarAutor(txtid.getText(), txtNombre.getText(), txtApellido.getText(), txtPais.getText());
        if (respuesta.equals("OK")) {
            JOptionPane.showMessageDialog(this, "Registrado correctamente");
            limpiar();
            tablaAutor.setModel(GestionAutor.getModeloAutor());
            ConexionOracol co = new ConexionOracol();
            

        } else {
            JOptionPane.showMessageDialog(this, respuesta);
        }

    }

    private void limpiar() {
        txtid.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtPais.setText("");

    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FAutor dialog = new FAutor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAutor;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
