package Formularios;

import Datos.ArchivoAutor;
import Datos.ArchivoEditorial;
import Datos.ArchivoLibro;
import Datos.ArchivoProveedor;
import Datos.Autor;
import Datos.ConexionOracol;
import Datos.Editorial;
import Datos.Libro;
import Datos.Proveedor;
import Logico.GestionLibro;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class FLibros extends javax.swing.JFrame {

    /**
     * Creates new form FLibros
     */
    public FLibros() {
        initComponents();
        cargarComboEditorial(ArchivoEditorial.getEditorial());
        cargarComboAutor(ArchivoAutor.getAutor());
        cargarComboProveedor(ArchivoProveedor.getProveedor());
        pintarTabla();
    }

    public void pintarTabla() {
        ArrayList<Libro> listaLibro = ArchivoLibro.getLibro();
        tablaLibro.setModel(GestionLibro.getModeloLibro(listaLibro));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbProveedor = new javax.swing.JComboBox<>();
        txtCategoria = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        cmbEditorial1 = new javax.swing.JComboBox<>();
        cmbAutor = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibro = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCategoria1 = new javax.swing.JTextField();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 30, 690, 10);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel7.setText("Registrar libros");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 0, 210, 30);

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidad);
        txtCantidad.setBounds(400, 140, 180, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Categoria");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 110, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Titulo");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 80, 80, 30);

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        jPanel1.add(txtTitulo);
        txtTitulo.setBounds(100, 80, 180, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("ISBN");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(320, 80, 80, 30);

        txtIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIsbnActionPerformed(evt);
            }
        });
        jPanel1.add(txtIsbn);
        txtIsbn.setBounds(400, 80, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Cantidad");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 140, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Precio");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(320, 110, 80, 30);

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecio);
        txtPrecio.setBounds(400, 110, 180, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Editorial");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 140, 80, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Autor");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 170, 80, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addressbook_addressbook_edition_librodedireccion_2817 (1).png"))); // NOI18N
        jButton1.setText("modificar");
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 250, 120, 40);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Libro"));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Año");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 140, 60, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Proveedor");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(310, 110, 80, 30);

        cmbProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        cmbProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(cmbProveedor);
        cmbProveedor.setBounds(390, 110, 180, 30);

        txtCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaActionPerformed(evt);
            }
        });
        jPanel2.add(txtCategoria);
        txtCategoria.setBounds(90, 50, 180, 30);

        txtAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAñoActionPerformed(evt);
            }
        });
        jPanel2.add(txtAño);
        txtAño.setBounds(90, 140, 180, 30);

        cmbEditorial1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        cmbEditorial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEditorial1ActionPerformed(evt);
            }
        });
        jPanel2.add(cmbEditorial1);
        cmbEditorial1.setBounds(90, 80, 180, 30);

        cmbAutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        cmbAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAutorActionPerformed(evt);
            }
        });
        jPanel2.add(cmbAutor);
        cmbAutor.setBounds(90, 110, 180, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 60, 700, 180);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addressbook_addressbook_add_librodedireccion_2815.png"))); // NOI18N
        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(130, 250, 107, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search_book_open_search_locate_6178.png"))); // NOI18N
        jButton3.setText("Buscar");
        jPanel1.add(jButton3);
        jButton3.setBounds(360, 310, 120, 40);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(80, 310, 270, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("ISBN");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 310, 80, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addressbook_addressbook_delete_librodedireccion_2816.png"))); // NOI18N
        jButton4.setText("Eliminar");
        jPanel1.add(jButton4);
        jButton4.setBounds(360, 250, 120, 40);

        jScrollPane1.setViewportView(tablaLibro);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 370, 730, 160);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/emblemunreadable_93487.png"))); // NOI18N
        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(560, 300, 120, 50);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Año");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 200, 60, 30);

        jLabel14.setText("Proveedor");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(320, 140, 70, 30);

        txtCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoria1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCategoria1);
        txtCategoria1.setBounds(100, 110, 180, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 760, 560);

        setSize(new java.awt.Dimension(771, 603));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsbnActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        agregar();
        pintarTabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProveedorActionPerformed

    private void txtCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoria1ActionPerformed

    private void txtAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñoActionPerformed

    private void cmbEditorial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEditorial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEditorial1ActionPerformed

    private void cmbAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAutorActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaActionPerformed

    private int posicionAutor() {
        int posicion = cmbAutor.getSelectedIndex();
        return posicion - 1;
    }

    private int posicionProveedor() {
        int posicion = cmbProveedor.getSelectedIndex();
        return posicion - 1;
    }

    private int posicionEditorial() {
        int posicion = cmbEditorial1.getSelectedIndex();
        return posicion - 1;
    }

    private Libro agregarLibros() {
        Proveedor proveedor = GestionLibro.asignarProveedor(posicionProveedor());
        Autor autor = GestionLibro.asignarAutor(posicionAutor());
        Editorial editorial = GestionLibro.asignarEditorial(posicionEditorial());
        Libro libro = new Libro(txtTitulo.getText().trim(), txtCategoria.getText().trim(), txtIsbn.getText().trim(), Integer.parseInt(txtAño.getText().trim()),
                Integer.parseInt(txtCantidad.getText().trim()), Integer.parseInt(txtPrecio.getText().trim()),
                editorial, autor, proveedor);
        return libro;
    }

    private String validar() {
        return GestionLibro.registrarLibro(txtTitulo.getText().trim(), txtCategoria.getText().trim(), txtIsbn.getText().trim(), txtAño.getText().trim(),
                txtCantidad.getText().trim(), txtPrecio.getText().trim(),
                GestionLibro.asignarEditorial(posicionEditorial()),
                GestionLibro.asignarAutor(posicionAutor()),
                GestionLibro.asignarProveedor(posicionProveedor()));
    }

    private void agregar() {

        String resultado = validar();
        if (cmbAutor.getSelectedItem().toString().equals("Seleccionar") || cmbProveedor.getSelectedItem().toString().equals("Seleccionar") || cmbEditorial1.getSelectedItem().toString().equals("Seleccionar")) {
            JOptionPane.showMessageDialog(this, "Rellene todo los campos");
        } else if (resultado.equals("OK")) {
            Libro libro = agregarLibros();
            JOptionPane.showMessageDialog(rootPane, GestionLibro.AgregarLibro(libro));
            limpiar();
            pintarTabla();
            ConexionOracol co = new ConexionOracol();

        } else {
            JOptionPane.showMessageDialog(this, resultado);
        }

    }

    private void limpiar() {
        txtAño.setText("");
        txtCantidad.setText("");
        txtCategoria.setText("");
        txtIsbn.setText("");
        txtPrecio.setText("");
        txtPrecio.setText("");
        txtTitulo.setText("");
        cmbEditorial1.setSelectedItem("Seleccionar");
        cmbAutor.setSelectedItem("Seleccioniar");
        cmbProveedor.setSelectedItem("Seleccionar");
    }

    private void cargarComboEditorial(ArrayList<Editorial> lista) {
        for (Editorial e : lista) {
            cmbEditorial1.addItem(e.getNombre() + "-" + e.getCodigo());

        }

    }

    private void cargarComboAutor(ArrayList<Autor> lista) {
        for (Autor e : lista) {
            cmbAutor.addItem(e.getNombre() + " " + e.getApellido());

        }

    }

    private void cargarComboProveedor(ArrayList<Proveedor> lista) {
        for (Proveedor e : lista) {
            cmbProveedor.addItem(e.getNombre() + " " + e.getApellido());

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAutor;
    private javax.swing.JComboBox<String> cmbEditorial1;
    private javax.swing.JComboBox<String> cmbProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable tablaLibro;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCategoria1;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
