package Formularios;

import Datos.ArchivoLibro;
import Datos.ArchivoPrestamo;
import Datos.ArchivoPersona;
import Datos.ConexionOracol;
import Datos.Libro;
import Datos.Persona;
import Datos.Prestamo;
import Logico.GestionLibro;
import Logico.GestionPrestamo;
import Logico.GestionPersona;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class FPrestamo extends javax.swing.JFrame {

    /**
     * Creates new form Prestamos
     */
    public FPrestamo() {
        initComponents();
        botonDevolucion.setVisible(false);
        pintar();

    }

    public void pintar() {
        ArrayList<Prestamo> listaPrestamo = ArchivoPrestamo.getPrestamo();
        try {
            TablaPrestamo.setModel(GestionPrestamo.getModeloPrestamo());
        } catch (Exception e) {
            System.out.println(e);
        }

////        if (listaPrestamo == null) {
////
////        } else {
////            TablaPrestamo.setModel(GestionPrestamo.getModeloPrestamo());
////        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        cmbMes = new javax.swing.JComboBox<>();
        cmbAño = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        cmbDia = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        botonIsbn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPrestamo = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmbEleccion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboAño = new javax.swing.JComboBox<>();
        comboMes = new javax.swing.JComboBox<>();
        comboDia = new javax.swing.JComboBox<>();
        botonDevolucion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Prestatario"));
        jPanel3.setToolTipText("Prestatario");
        jPanel3.setLayout(null);

        txtNombre.setEditable(false);
        jPanel3.add(txtNombre);
        txtNombre.setBounds(90, 20, 210, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Identificación");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(340, 20, 80, 30);
        jPanel3.add(txtId);
        txtId.setBounds(430, 20, 120, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/business_man_usersearch_thesearch_theclient_2356.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(550, 20, 90, 30);

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre ", "Diciembre", " " }));
        cmbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesActionPerformed(evt);
            }
        });
        jPanel3.add(cmbMes);
        cmbMes.setBounds(500, 50, 80, 30);

        cmbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2020", "2021", "2022", "2023" }));
        cmbAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAñoActionPerformed(evt);
            }
        });
        jPanel3.add(cmbAño);
        cmbAño.setBounds(430, 50, 70, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Nombre");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 20, 70, 30);

        fechaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechaLabel.setText("F-Limite");
        jPanel3.add(fechaLabel);
        fechaLabel.setBounds(340, 50, 80, 30);

        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", " " }));
        cmbDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDiaActionPerformed(evt);
            }
        });
        jPanel3.add(cmbDia);
        cmbDia.setBounds(580, 50, 60, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 130, 650, 110);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Libro"));
        jPanel4.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Categoria");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(10, 80, 70, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Titulo");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 50, 60, 30);

        txtCategoria.setEditable(false);
        txtCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaActionPerformed(evt);
            }
        });
        jPanel4.add(txtCategoria);
        txtCategoria.setBounds(80, 80, 140, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("ISBN");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 20, 70, 30);

        txtIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIsbnActionPerformed(evt);
            }
        });
        jPanel4.add(txtIsbn);
        txtIsbn.setBounds(80, 20, 140, 30);

        botonIsbn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search_book_open_search_locate_6178.png"))); // NOI18N
        botonIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIsbnActionPerformed(evt);
            }
        });
        jPanel4.add(botonIsbn);
        botonIsbn.setBounds(220, 20, 80, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(60, 210, 452, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/book-bookmark-icon_34486.png"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(520, 30, 70, 70);

        txtTitulo.setEditable(false);
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        jPanel4.add(txtTitulo);
        txtTitulo.setBounds(80, 50, 140, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(10, 240, 650, 130);

        TablaPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPrestamoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaPrestamo);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 400, 650, 210);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/emblemunreadable_93487.png"))); // NOI18N
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(540, 620, 110, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1486485588-add-create-new-math-sign-cross-plus_81186.png"))); // NOI18N
        jButton4.setText("Registrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(390, 620, 120, 30);

        jPanel1.setLayout(null);

        cmbEleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGISTRAR PRESTAMO", "DEVOLUCIONES" }));
        cmbEleccion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEleccionItemStateChanged(evt);
            }
        });
        cmbEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEleccionActionPerformed(evt);
            }
        });
        jPanel1.add(cmbEleccion);
        cmbEleccion.setBounds(18, 5, 160, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("F-Devolución");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 50, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("FECHA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 40, 50, 30);

        comboAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2020", "2021", "2022", "2023" }));
        comboAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAñoActionPerformed(evt);
            }
        });
        jPanel1.add(comboAño);
        comboAño.setBounds(60, 40, 80, 30);

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre ", "Diciembre", " " }));
        comboMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMesActionPerformed(evt);
            }
        });
        jPanel1.add(comboMes);
        comboMes.setBounds(140, 40, 90, 30);

        comboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", " " }));
        comboDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiaActionPerformed(evt);
            }
        });
        jPanel1.add(comboDia);
        comboDia.setBounds(230, 40, 80, 30);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(330, 10, 320, 100);

        botonDevolucion.setText("Devolucion");
        botonDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDevolucionActionPerformed(evt);
            }
        });
        jPanel2.add(botonDevolucion);
        botonDevolucion.setBounds(273, 620, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-10, 0, 660, 760);

        setSize(new java.awt.Dimension(664, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void botonIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIsbnActionPerformed
        buscarLibro(ArchivoLibro.getLibro());
    }//GEN-LAST:event_botonIsbnActionPerformed

    private void txtIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsbnActionPerformed

    private void cmbEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEleccionActionPerformed

    private void comboMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMesActionPerformed
        comboMes();
    }//GEN-LAST:event_comboMesActionPerformed

    private void comboDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDiaActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        buscarPersona(ArchivoPersona.getPrestatario());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAñoActionPerformed
        comboAño();
    }//GEN-LAST:event_comboAñoActionPerformed

    private void cmbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDiaActionPerformed

    private void cmbAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAñoActionPerformed
        comboAño2();
    }//GEN-LAST:event_cmbAñoActionPerformed

    private void cmbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesActionPerformed
        comboMes2();
    }//GEN-LAST:event_cmbMesActionPerformed

    private void cmbEleccionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEleccionItemStateChanged
        elegir();
    }//GEN-LAST:event_cmbEleccionItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Registrar();
        pintar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void botonDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevolucionActionPerformed
        devolucion();

    }//GEN-LAST:event_botonDevolucionActionPerformed

    private void TablaPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPrestamoMouseClicked
        pintar(TablaPrestamo.rowAtPoint(evt.getPoint()));
    }//GEN-LAST:event_TablaPrestamoMouseClicked

    private void txtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaActionPerformed

    private void pintar(int fila) {
        txtId.setText(String.valueOf(TablaPrestamo.getValueAt(fila, 0)));
        txtNombre.setText(String.valueOf(TablaPrestamo.getValueAt(fila, 1)));
        txtIsbn.setText(String.valueOf(TablaPrestamo.getValueAt(fila, 2)));
        txtTitulo.setText(String.valueOf(TablaPrestamo.getValueAt(fila, 3)));
    }

    private void devolucion() {
        String respuesta = GestionPrestamo.validarDevolucion(comboDia.getSelectedItem().toString(), comboMes.getSelectedItem().toString(), comboAño.getSelectedItem().toString());
        if (respuesta.equals("OK")) {
            GestionPrestamo.devolucion(txtId.getText().trim(), fecha(comboDia.getSelectedItem().toString(), comboMes.getSelectedItem().toString(), comboAño.getSelectedItem().toString()),
                    txtIsbn.getText().trim());
            pintar();
            ConexionOracol co = new ConexionOracol();
        } else {
            JOptionPane.showMessageDialog(this, respuesta);
        }
    }

    private void Registrar() {
        Persona persona = asignarPersona(ArchivoPersona.getPrestatario(), txtId.getText().trim());
        System.out.println(persona.getIdentificacion());
        Prestamo p;
        p = new Prestamo(asignarPersona(ArchivoPersona.getPrestatario(), txtId.getText().trim()), asignarLibro(ArchivoLibro.getLibro(), txtIsbn.getText().trim()),
                fecha(comboDia.getSelectedItem().toString(), comboMes.getSelectedItem().toString(), comboAño.getSelectedItem().toString()),
                fecha(cmbDia.getSelectedItem().toString(), cmbMes.getSelectedItem().toString(), cmbAño.getSelectedItem().toString()));
        pintar();
        JOptionPane.showMessageDialog(rootPane, GestionPrestamo.registrarPrestamo(p));
        ConexionOracol co = new ConexionOracol();

    }

    private String fecha(String dia, String mes, String año) {
        return dia + "/" + mes + "/" + año;
    }

    public static Persona asignarPersona(ArrayList<Persona> listaPersona, String id) {

        for (Persona p : listaPersona) {
            if (p.getIdentificacion().equals(id)) {
                return p;
            }
        }
        return null;
    }

    public static Libro asignarLibro(ArrayList<Libro> listaLibro, String isbn) {

        for (Libro l : listaLibro) {
            if (l.getIsbn().equals(isbn)) {
                return l;
            }
        }
        return null;
    }

    private void elegir() {
        if (cmbEleccion.getSelectedItem().toString().equals("DEVOLUCIONES")) {
            botonIsbn.setVisible(false);
            txtIsbn.setEnabled(false);
            fechaLabel.setVisible(false);
            cmbAño.setVisible(false);
            cmbMes.setVisible(false);
            cmbDia.setVisible(false);
            botonDevolucion.setVisible(true);
        } else {
            botonIsbn.setVisible(true);
            fechaLabel.setVisible(true);
            cmbAño.setVisible(true);
            cmbMes.setVisible(true);
            cmbDia.setVisible(true);
            botonDevolucion.setVisible(false);
        }

    }

    public void buscarPersona(ArrayList<Persona> listaPersona) {
        String identificacion = txtId.getText().trim();
        try {
            for (Persona p : listaPersona) {
                if (p.getIdentificacion().equals(identificacion)) {
                    txtNombre.setText(p.getNombre() + " " + p.getApellido());

                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No encontrado");
        }
    }

    public void buscarLibro(ArrayList<Libro> listaLibro) {
        String isbn = txtIsbn.getText();
        for (Libro l : listaLibro) {
            if (l.getIsbn().equals(isbn)) {
                txtTitulo.setText(l.getTitulo());
                txtCategoria.setText(l.getCategoria());
            } else {

            }
        }

    }

    public void comboAño() {
        if (!comboAño.getSelectedItem().equals("Año")) {
            comboMes.setEnabled(true);

        } else {
            comboDia.setEnabled(false);
            comboMes.setEnabled(false);
            comboMes.setSelectedItem("Mes");
            comboDia.setSelectedItem("Dia");

        }

    }

    public void comboMes() {
        if (comboAño.getSelectedItem().equals("Año")) {
            comboDia.setEnabled(false);
            comboMes.setEnabled(false);
            comboMes.setSelectedItem("Mes");
            comboDia.setSelectedItem("Dia");
        }
        comboDia.removeAllItems();
        if (!comboMes.getSelectedItem().equals("Mes")) {
            comboDia.addItem("Dia");
            comboDia.setEnabled(true);
            if (comboMes.getSelectedItem().equals("Abril") || comboMes.getSelectedItem().equals("junio")
                    || comboMes.getSelectedItem().equals("Septiembre") || comboMes.getSelectedItem().equals("Noviembre")) {

                for (int i = 1; i <= 30; i++) {
                    comboDia.addItem("" + i);
                }
            } else {

                if (comboMes.getSelectedItem().equals("Febrero")) {
                    int anio = Integer.parseInt(comboAño.getSelectedItem().toString());

                    if ((anio % 4 == 0) && ((anio % 100 != 0) || (anio % 400 == 0))) {
                        for (int i = 1; i <= 29; i++) {
                            comboDia.addItem("" + i);
                        }
                    } else {
                        for (int i = 1; i <= 28; i++) {
                            comboDia.addItem("" + i);
                        }
                    }

                } else {
                    for (int i = 1; i <= 31; i++) {
                        comboDia.addItem("" + i);
                    }
                }

            }
        } else {
            comboDia.addItem("Dia");
            comboDia.setEnabled(false);
            comboDia.setSelectedItem("Dia");
        }
    }

    public void comboAño2() {
        if (!cmbAño.getSelectedItem().equals("Año")) {
            cmbMes.setEnabled(true);

        } else {
            cmbDia.setEnabled(false);
            cmbMes.setEnabled(false);
            cmbMes.setSelectedItem("Mes");
            cmbDia.setSelectedItem("Dia");

        }

    }

    public void comboMes2() {
        if (cmbAño.getSelectedItem().equals("Año")) {
            cmbDia.setEnabled(false);
            cmbMes.setEnabled(false);
            cmbMes.setSelectedItem("Mes");
            cmbDia.setSelectedItem("Dia");
        }
        cmbDia.removeAllItems();
        if (!cmbMes.getSelectedItem().equals("Mes")) {
            cmbDia.addItem("Dia");
            cmbDia.setEnabled(true);
            if (cmbMes.getSelectedItem().equals("Abril") || cmbMes.getSelectedItem().equals("junio")
                    || cmbMes.getSelectedItem().equals("Septiembre") || cmbMes.getSelectedItem().equals("Noviembre")) {

                for (int i = 1; i <= 30; i++) {
                    cmbDia.addItem("" + i);
                }
            } else {

                if (cmbMes.getSelectedItem().equals("Febrero")) {
                    int anio = Integer.parseInt(cmbAño.getSelectedItem().toString());

                    if ((anio % 4 == 0) && ((anio % 100 != 0) || (anio % 400 == 0))) {
                        for (int i = 1; i <= 29; i++) {
                            cmbDia.addItem("" + i);
                        }
                    } else {
                        for (int i = 1; i <= 28; i++) {
                            cmbDia.addItem("" + i);
                        }
                    }

                } else {
                    for (int i = 1; i <= 31; i++) {
                        cmbDia.addItem("" + i);
                    }
                }

            }
        } else {
            cmbDia.addItem("Dia");
            cmbDia.setEnabled(false);
            cmbDia.setSelectedItem("Dia");
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPersona.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPersona.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPersona.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPersona.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrestamo().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPrestamo;
    private javax.swing.JButton botonDevolucion;
    private javax.swing.JButton botonIsbn;
    private javax.swing.JComboBox<String> cmbAño;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbEleccion;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JComboBox<String> comboAño;
    private javax.swing.JComboBox<String> comboDia;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
